const AntiSpam = require("./Schema/AntiSpam")
const InviteSystem = require("./Schema/Invite-System")
const invites = require("./Schema/Invites")
const InviteTracker = require("./Schema/InviteTracker")
const Premium = require("./Schema/Premium")
const Racks = require("./Schema/Racks")
const BoosterRack = require("./Schema/Racks/Booster-Rack")
const FreeRack = require("./Schema/Racks/Free-Rack")
const PremiumRack1 = require("./Schema/Racks/Premium-Rack1")
const PremiumRack2 = require("./Schema/Racks/Premium-Rack2")
const PremiumRack3 = require("./Schema/Racks/Premium-Rack3")
const Rack1 = require("./Schema/Racks/Rack1")
const Rack2 = require("./Schema/Racks/Rack2")
const Rack3 = require("./Schema/Racks/Rack3")
const Rack4 = require("./Schema/Racks/Rack4")
const Rack5 = require("./Schema/Racks/Rack5")
const Ranking = require("./Schema/Ranking/Ranking")
const balance = require("./Schema/RoverCoins/balance")
const RcCooldowns = require("./Schema/RoverCoins/RcCooldowns")
const SystemRemind = require("./Schema/RoverCoins/SystemRemind")
const TotalCoins = require("./Schema/RoverCoins/TotalCoins")
const BotConfig = require("./Schema/Shop/BotConfig")
const ShopRules = require("./Schema/Shop/Rules")
const ShopCreation = require("./Schema/Shop/ShopCreation")
const StaffRank = require("./Schema/Staff-System/StaffRank")
const UseFullLinks = require("./Schema/Staff-System/UseFullLinks")
const PremiumBot = require("./Schema/Storage/ShopBots/PremiumBot")
const RegularBot = require("./Schema/Storage/ShopBots/RegularBot")
const PremiumServer = require("./Schema/Storage/VMServers/PremiumServer")
const RegularServer = require("./Schema/Storage/VMServers/RegularServer")
const CreateTicket = require("./Schema/TicketSystem/CreateTicket")
const GuildStats = require("./Schema/TicketSystem/GuildStats")

const Enmap = require("enmap");


module.exports = async Roverdev =>  {
    Roverdev.AntiSpam = AntiSpam
    Roverdev.balance = balance
    Roverdev.InviteSystem = InviteSystem
    Roverdev.invites = invites
    Roverdev.InviteTracker = InviteTracker
    Roverdev.Premium = Premium
    Roverdev.Racks = Racks
    Roverdev.BoosterRack = BoosterRack
    Roverdev.FreeRack = FreeRack
    Roverdev.PremiumRack1 = PremiumRack1
    Roverdev.PremiumRack2 = PremiumRack2
    Roverdev.PremiumRack3 = PremiumRack3
    Roverdev.Rack1 = Rack1
    Roverdev.Rack2 = Rack2
    Roverdev.Rack3 = Rack3
    Roverdev.Rack4 = Rack4
    Roverdev.Rack5 = Rack5
    Roverdev.Ranking = Ranking
    Roverdev.RcCooldowns = RcCooldowns
    Roverdev.SystemRemind = SystemRemind
    Roverdev.TotalCoins = TotalCoins
    Roverdev.BotConfig = BotConfig
    Roverdev.ShopRules = ShopRules
    Roverdev.ShopCreation = ShopCreation
    Roverdev.StaffRank = StaffRank
    Roverdev.UseFullLinks = UseFullLinks
    Roverdev.PremiumBot = PremiumBot
    Roverdev.RegularBot = RegularBot
    Roverdev.PremiumServer = PremiumServer
    Roverdev.RegularServer = RegularServer
    Roverdev.CreateTicket = CreateTicket
    Roverdev.GuildStats = GuildStats
}
